### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [ralphabb/GNN-RNI#3]
Hello,

Thank you for the nice paper and code. I am playing with EXP dataset and found that some of the graphs are not planar (for example 5-th graph is not planar according to ```nx.algorithms.planarity.check_planarity```). From reading paper, I thought each data has two graphs and both of them should be planar. Do I misunderstand something? Thank you!

**Comment by Chen-Cai-OSU** [comment]
I somehow looked at CEXP instead of EXP. So EXP are all planar but not CEXP?

**Comment by ralphabb** [comment]
Hi,
Indeed, some CEXP instances are not guaranteed to be planar. CEXP is designed such that the first graph extends the second graph in an EXP pair with additional edges. Hence, the second graph in a pair is always planar, as it is identical to EXP, but the first graph could not be as the new edges could violate planarity. Nonetheless, the pairs are much easier to distinguish than in EXP, as they no longer have an identical number of edges or identical node degrees.

 I hope this clarifies things.
Best,
Ralph

**Comment by Chen-Cai-OSU** [comment]
Thank you very much! I have one more question: how is the node feature set? I saw there is one-dim feature that consists of only 0 and 1. Is this some kind of one-hot encoding?
