### ISSUE TITLE
how is the node feature set?

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [ralphabb/GNN-RNI#4]
I have one more question: how is the node feature set? I saw there is one-dim feature that consists of only 0 and 1. Is this some kind of one-hot encoding? Thank you!

_Originally posted by @Chen-Cai-OSU in https://github.com/ralphabb/GNN-RNI/issues/3#issuecomment-919708072_

**Comment by ralphabb** [comment]
Hello, the node feature indeed consists of a binary flag, representing whether a node is a literal or a disjunctive clause. 
Cheers,
Ralph

**Comment by Chen-Cai-OSU** [comment]
Thank you!
