### ISSUE TITLE
3-GNN.py can't run

### ISSUE THREAD

**Issue by xdmdtz123** [ralphabb/GNN-RNI#7]
![图片](https://user-images.githubusercontent.com/61136601/157405288-89663f79-549c-4929-87ee-ef72dc0c7a4e.png)
I copied and pasted the ./3-GNNSetup/isomorphism.h file and replaced the ./k-gnn/cpu/isomorphism.h file. Then run "Then run sudo python setup.py install" successful. But when I running "python 3-GNN.py -layers 2 -width 64", there will be the following error messages.
![图片](https://user-images.githubusercontent.com/61136601/157407247-b0ebb321-bb91-4e3d-8039-519db5b9969f.png)

**Comment by ralphabb** [comment]
Hello again! I think you need to clear your processed files from the previous run. So what usually happens is that every dataset is "processed" the first time to include the new attributes. If you started with the RNI model, your processing won't compute the iso_types, so this will throw an error. Hence, to fix this bug, you should delete the processed folder and rerun the same command. I hope this helps.
Best,
Ralph

**Comment by xdmdtz123** [comment]
The code has been able to run. Thank you for your help.
