### ISSUE TITLE
some questions about 3-GNN

### ISSUE THREAD

**Issue by xdmdtz123** [ralphabb/GNN-RNI#8]
Deer author:
  Sorry to bother you again. I have some doubts about the code of 3-GNN, so I want to consult you.
  1.I found the value of num_ i_3 is 1, in other words, dataset.data. iso_type_3 has only one same result. Is it correct to take it as the input of GNN? Or did I run the code wrong?
![图片](https://user-images.githubusercontent.com/61136601/158843043-71c80a41-9149-422e-b490-d1449f26b9b7.png)
![图片](https://user-images.githubusercontent.com/61136601/158843534-4f9b5a52-ad18-4255-aaa4-541ecde831bc.png)
  2.The following is the definition of iso_type. If there is no error in iso_type_3 mentioned above,Does that mean all tuples in the processed graph have same isomorphic type?What is the reason for this result?
![图片](https://user-images.githubusercontent.com/61136601/158848531-5f210f23-e991-4b90-920f-6d71f9d2a5f8.png)
  3.I find my result is very poor, so what's wrong with me?
     The command I run is "python 3-GNN.py -layers 8 -width 64 -learnRate 0.0005 -epochs 500", and because of the limitation of computer performance, I changed BATCH from 20 to 5.
![图片](https://user-images.githubusercontent.com/61136601/158851437-fb5af551-0637-459d-b497-d75658098846.png)
  Looking forward to your reply, thank you.

**Comment by ralphabb** [comment]
Hi,  I don't think this should be the case that you have 1 iso type. This is likely an error in setup. The definition you give in 2) is correct, and there should be multiple iso types in the dataset. As a result, I suspect that having 1 iso type is why you have the poor performance in 3. Have you set up the codebase properly? To make the full 3-WL setup work, you should set up the files as described in the readme. "To use the 3-GNN implementation, found in 3-GNN.py, you must first replace cpu/isomorphism.h within k-gnn with the same file found in 3-GNN Setup, and set up the project again."

**Comment by xdmdtz123** [comment]
Thank you for your reply. The reason for the error is found. It is the problem of pyg version. After changing version 1.7 to 1.4, the accuracy has changed and dataset.data.iso_type_3 has become three-dimensional.
